default: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'aws-0-eu-central-1.pooler.supabase.com' %>
  port: <%= ENV['DB_PORT'] || 6543 %>
  username: <%= ENV['DB_USER'] || 'postgres.ipbphqqlssnietcqyfbh' %>
  password: <%= ENV['DB_PASSWORD'] || 'z3j_V6KLQifm-CC' %>
  database: <%= ENV['DB_NAME'] || 'postgres' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reconnect: true
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
